package chat

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/benaskins/axon"
	fact "github.com/benaskins/axon-fact"
	loop "github.com/benaskins/axon-loop"
	tool "github.com/benaskins/axon-tool"
	"github.com/benaskins/axon/sse"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

const maxChatRequestSize = 1 << 20 // 1MB

var (
	chatLLMCallsTotal   metric.Int64Counter
	chatLLMCallDuration metric.Float64Histogram
	chatLLMTokensTotal  metric.Float64Counter
)

func init() {
	meter := axon.MeterProvider().Meter("axon-chat")

	var err error
	chatLLMCallsTotal, err = meter.Int64Counter(
		"chat.llm.calls.total",
		metric.WithDescription("Total LLM conversation loop calls by model and outcome"),
	)
	if err != nil {
		panic("axon-chat: failed to create llm calls counter: " + err.Error())
	}

	chatLLMCallDuration, err = meter.Float64Histogram(
		"chat.llm.call.duration",
		metric.WithDescription("LLM conversation loop duration in seconds"),
		metric.WithUnit("s"),
	)
	if err != nil {
		panic("axon-chat: failed to create llm duration histogram: " + err.Error())
	}

	chatLLMTokensTotal, err = meter.Float64Counter(
		"chat.llm.tokens.generated.total",
		metric.WithDescription("Total tokens generated by LLM model"),
	)
	if err != nil {
		panic("axon-chat: failed to create tokens counter: " + err.Error())
	}
}

type chatRequest struct {
	Model          string         `json:"model"`
	ConversationID string         `json:"conversation_id,omitempty"`
	AgentSlug      string         `json:"agent_slug,omitempty"`
	Messages       []loop.Message `json:"messages"`
	Think          *bool          `json:"think,omitempty"`
	Options        map[string]any `json:"options,omitempty"`
	Tools          []string       `json:"tools,omitempty"`
}

type chatHandler struct {
	defaultModel    string
	llm             loop.LLMClient
	store           Store
	eventStore      fact.EventStore
	shutdownCtx     context.Context
	bgTasks         *sync.WaitGroup
	eventBus        *sse.EventBus[Event]
	searcher        Searcher
	toolRouter      *ToolRouter
	taskRunner      TaskRunner
	weather         WeatherProvider
	pageFetcher     *PageFetcher
	searchQualifier *SearchQualifier
	extraTools      map[string]tool.ToolDef
	memoryRecaller  MemoryRecaller
	idleExtractor   *IdleExtractor
	analytics       AnalyticsEmitter
	pollInterval    time.Duration
}

func newChatHandler(defaultModel string, llm loop.LLMClient, store Store, shutdownCtx context.Context, eventBus *sse.EventBus[Event]) *chatHandler {
	return &chatHandler{
		defaultModel: defaultModel,
		llm:          llm,
		store:        store,
		shutdownCtx:  shutdownCtx,
		bgTasks:      &sync.WaitGroup{},
		eventBus:     eventBus,
	}
}

// emit appends a domain event to the event store. Returns nil if no event store is configured.
func (h *chatHandler) emit(ctx context.Context, stream string, data EventTyper, meta map[string]string) error {
	return emitEvent(ctx, h.eventStore, stream, data, meta)
}

func (h *chatHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		axon.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, maxChatRequestSize)
	var req chatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		axon.WriteError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if len(req.Messages) == 0 {
		axon.WriteError(w, http.StatusBadRequest, "messages must not be empty")
		return
	}

	// Verify agent ownership — the requesting user must own the agent
	if req.AgentSlug != "" && h.store != nil {
		ctx := r.Context()
		userID := axon.UserID(ctx)
		if _, err := h.store.GetAgentByUser(ctx, userID, req.AgentSlug); err != nil {
			if errors.Is(err, ErrAgentNotFound) {
				axon.WriteError(w, http.StatusNotFound, "agent not found")
			} else {
				slog.Error("failed to verify agent", "slug", req.AgentSlug, "error", err)
				axon.WriteError(w, http.StatusInternalServerError, "failed to verify agent")
			}
			return
		}
	}

	model := req.Model
	if model == "" {
		model = h.defaultModel
	}

	if h.llm == nil {
		axon.WriteError(w, http.StatusInternalServerError, "LLM client not configured")
		return
	}

	// Extract last user message content for persistence
	var userContent string
	for i := len(req.Messages) - 1; i >= 0; i-- {
		if req.Messages[i].Role == "user" {
			userContent = req.Messages[i].Content
			break
		}
	}

	h.runAgent(w, r, model, req.Messages, req.Think, req.Options, req.Tools, req.ConversationID, userContent, req.AgentSlug)
}

// SSETaskEvent represents a task submission event sent to the frontend.
type SSETaskEvent struct {
	TaskID      string `json:"task_id"`
	Type        string `json:"type"`        // "claude_session" | "image_generation"
	Status      string `json:"status"`      // "queued" | "running"
	Description string `json:"description"`
}

type sseEvent struct {
	Content         string        `json:"content"`
	Thinking        string        `json:"thinking,omitempty"`
	Done            bool          `json:"done"`
	TotalDurationMs *int64        `json:"total_duration_ms,omitempty"`
	ToolUse         string        `json:"tool_use,omitempty"`
	Task            *SSETaskEvent `json:"task,omitempty"`
}

func (h *chatHandler) runAgent(w http.ResponseWriter, r *http.Request, model string, messages []loop.Message, think *bool, options map[string]any, toolNames []string, conversationID string, userContent string, agentSlug string) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		axon.WriteError(w, http.StatusInternalServerError, "streaming not supported")
		return
	}

	sse.SetSSEHeaders(w)

	start := time.Now()
	var tokenCount float64

	sendEvent := func(event sseEvent) {
		data, err := json.Marshal(event)
		if err != nil {
			return
		}
		fmt.Fprintf(w, "data: %s\n\n", data)
		flusher.Flush()
	}

	// Extract system prompt for tool context
	var systemPrompt string
	if len(messages) > 0 && messages[0].Role == "system" {
		systemPrompt = messages[0].Content
	}

	// Build tool map from requested tool names
	tools := h.buildToolMap(toolNames, sendEvent, r, agentSlug, conversationID, systemPrompt)

	// Use tool router to filter tools based on user message
	if h.toolRouter != nil && len(tools) > 0 && userContent != "" {
		toolDefs := toolDefsFromMap(tools)
		routed, err := h.toolRouter.Route(r.Context(), userContent, toolDefs)
		if err != nil {
			slog.Warn("tool router error, proceeding with all tools", "error", err)
		} else {
			tools = filterToolNames(tools, routed)
		}
	}

	// Build the agent request
	agentReq := &loop.Request{
		Model:    model,
		Messages: messages,
		Stream:   true,
		Think:    think,
		Options:  options,
	}

	// Build tool context
	userID := axon.UserID(r.Context())
	username := axon.Username(r.Context())
	toolCtx := &tool.ToolContext{
		Ctx:            r.Context(),
		UserID:         userID,
		Username:       username,
		AgentSlug:      agentSlug,
		ConversationID: conversationID,
		SystemPrompt:   systemPrompt,
	}

	// Wire callbacks to SSE
	cb := loop.Callbacks{
		OnToken: func(token string) {
			tokenCount++
			sendEvent(sseEvent{Content: token})
		},
		OnThinking: func(token string) {
			tokenCount++
			sendEvent(sseEvent{Thinking: token})
		},
		OnToolUse: func(name string, args map[string]any) {
			desc := describeToolUse(name, args)
			if desc != "" {
				sendEvent(sseEvent{Content: desc})
			}
			sendEvent(sseEvent{ToolUse: name})
		},
		OnDone: func(durationMs int64) {
			sendEvent(sseEvent{Done: true, TotalDurationMs: &durationMs})
		},
	}

	// Run the conversation loop
	result, err := loop.Run(r.Context(), h.llm, agentReq, tools, toolCtx, cb)
	if err != nil {
		chatLLMCallsTotal.Add(r.Context(), 1, metric.WithAttributes(
			attribute.String("model", model), attribute.String("status", "error"),
		))
		slog.Error("agent run error", "error", err, "model", model)
		sendEvent(sseEvent{Content: "Error: " + err.Error(), Done: true})
		return
	}

	// Metrics
	duration := time.Since(start).Seconds()
	ctx := r.Context()
	modelAttr := metric.WithAttributes(attribute.String("model", model))
	chatLLMCallDuration.Record(ctx, duration, modelAttr)
	chatLLMCallsTotal.Add(ctx, 1, metric.WithAttributes(
		attribute.String("model", model), attribute.String("status", "ok"),
	))
	chatLLMTokensTotal.Add(ctx, tokenCount, modelAttr)

	// Analytics
	durationMs := time.Since(start).Milliseconds()
	if h.analytics != nil && agentSlug != "" {
		runID := axon.RunID(r.Context())
		userEvt := MessageEvent(agentSlug, userID, conversationID, "user", 0)
		userEvt.RunID = runID
		assistantEvt := MessageEvent(agentSlug, userID, conversationID, "assistant", durationMs)
		assistantEvt.RunID = runID
		h.analytics.Emit(userEvt, assistantEvt)
	}

	// Persist via events — projectors update the read model
	if conversationID != "" && h.eventStore != nil {
		stream := "conversation-" + conversationID

		if err := h.emit(r.Context(), stream, MessageAppended{Role: "user", Content: userContent}, nil); err != nil {
			slog.Error("failed to emit user message event", "error", err, "conversation_id", conversationID)
		}
		if err := h.emit(r.Context(), stream, MessageAppended{
			Role: "assistant", Content: result.Content,
			Thinking: result.Thinking, DurationMs: &durationMs,
		}, nil); err != nil {
			slog.Error("failed to emit assistant message event", "error", err, "conversation_id", conversationID)
		}

		if h.idleExtractor != nil && agentSlug != "" {
			h.idleExtractor.Touch(conversationID, agentSlug, userID)
		}

		conv, err := h.store.GetConversationByUser(r.Context(), userID, conversationID)
		if err == nil && conv.Title == nil {
			h.bgTasks.Add(1)
			go func() {
				defer h.bgTasks.Done()
				h.generateTitle(h.shutdownCtx, userID, conversationID, userContent, result.Content)
			}()
		}
	}
}

// describeToolUse returns a human-readable description of a tool call.
func describeToolUse(name string, args map[string]any) string {
	switch name {
	case "web_search":
		if q, ok := args["query"].(string); ok {
			return fmt.Sprintf("\n\n*Searching for \"%s\"...*\n\n", q)
		}
		return "\n\n*Searching the web...*\n\n"
	case "fetch_page":
		if u, ok := args["url"].(string); ok {
			return fmt.Sprintf("\n\n*Reading %s...*\n\n", u)
		}
		return "\n\n*Reading a web page...*\n\n"
	case "check_weather":
		if loc, ok := args["location"].(string); ok {
			return fmt.Sprintf("\n\n*Checking weather for %s...*\n\n", loc)
		}
		return "\n\n*Checking the weather...*\n\n"
	case "current_time":
		return "\n\n*Checking the time...*\n\n"
	case "use_claude":
		return "\n\n*Submitting a code change...*\n\n"
	default:
		return fmt.Sprintf("\n\n*Using %s...*\n\n", name)
	}
}

// toolDefsFromMap extracts ToolDef slice from a map.
func toolDefsFromMap(m map[string]tool.ToolDef) []tool.ToolDef {
	defs := make([]tool.ToolDef, 0, len(m))
	for _, d := range m {
		defs = append(defs, d)
	}
	return defs
}

// filterToolNames returns a subset of tools matching the routed tool names.
func filterToolNames(all map[string]tool.ToolDef, routed []string) map[string]tool.ToolDef {
	result := make(map[string]tool.ToolDef)
	for _, name := range routed {
		if def, ok := all[name]; ok {
			result[name] = def
		}
	}
	return result
}

func (h *chatHandler) generateTitle(shutdownCtx context.Context, userID string, conversationID string, userMsg string, assistantMsg string) {
	ctx, cancel := context.WithTimeout(shutdownCtx, 30*time.Second)
	defer cancel()

	messages := []loop.Message{
		{Role: "system", Content: "Generate a very short title (3-5 words) for this conversation. Respond with only the title, nothing else."},
		{Role: "user", Content: userMsg},
		{Role: "assistant", Content: assistantMsg},
		{Role: "user", Content: "What is a good 3-5 word title for this conversation?"},
	}

	var title strings.Builder
	err := h.llm.Chat(ctx, &loop.Request{
		Model:    h.defaultModel,
		Messages: messages,
	}, func(resp loop.Response) error {
		title.WriteString(resp.Content)
		return nil
	})

	if ctx.Err() != nil {
		slog.Info("title generation cancelled", "conversation_id", conversationID, "reason", ctx.Err())
		return
	}

	if err != nil {
		slog.Warn("title generation failed", "conversation_id", conversationID, "error", err)
		return
	}
	titleStr := sanitizeTitle(title.String())
	if titleStr != "" {
		stream := "conversation-" + conversationID
		meta := map[string]string{"user_id": userID}
		h.emit(ctx, stream, ConversationTitled{Title: titleStr}, meta)
	}
}

// sanitizeTitle cleans up LLM-generated titles by stripping quotes and markdown.
func sanitizeTitle(raw string) string {
	s := strings.TrimSpace(raw)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			s = s[1 : len(s)-1]
		}
	}
	s = strings.TrimPrefix(s, "**")
	s = strings.TrimSuffix(s, "**")
	return strings.TrimSpace(s)
}

// pollTaskCompletion polls the task runner for a task's status and publishes an event when done.
func (h *chatHandler) pollTaskCompletion(taskID string) {
	interval := h.pollInterval
	if interval == 0 {
		interval = 10 * time.Second
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	timeout := time.After(12 * time.Minute)

	for {
		select {
		case <-ticker.C:
			status, err := h.taskRunner.GetTaskStatus(h.shutdownCtx, taskID)
			if err != nil {
				slog.Warn("failed to poll task status", "task_id", taskID, "error", err)
				continue
			}

			switch status.Status {
			case "completed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID:  taskID,
						Status:  "completed",
						Summary: status.Summary,
					}})
				}
				return
			case "failed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID: taskID,
						Status: "failed",
						Error:  status.Error,
					}})
				}
				return
			}
		case <-timeout:
			slog.Warn("task polling timed out", "task_id", taskID)
			if h.eventBus != nil {
				h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
					TaskID: taskID,
					Status: "failed",
					Error:  "timed out waiting for task completion",
				}})
			}
			return
		case <-h.shutdownCtx.Done():
			return
		}
	}
}

// dayOrNight returns a human-readable time-of-day string.
func dayOrNight(isDay bool) string {
	if isDay {
		return "Daytime"
	}
	return "Nighttime"
}

// WaitForBackgroundTasks blocks until all background tasks complete.
// Also flushes any pending idle extractions.
func (h *chatHandler) WaitForBackgroundTasks() {
	if h.idleExtractor != nil {
		h.idleExtractor.FlushAll()
	}
	h.bgTasks.Wait()
}


