package chat //  (NSFW detector is a safety feature)

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/benaskins/axon"
	"github.com/benaskins/axon/sse"
	streamfilter "github.com/benaskins/axon/stream"

	"github.com/google/uuid"
	ollamaapi "github.com/ollama/ollama/api"
	"github.com/prometheus/client_golang/prometheus"
)

const maxChatRequestSize = 1 << 20 // 1MB

var (
	chatRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "chat_requests_total",
			Help: "Total chat requests by model and status",
		},
		[]string{"model", "status"},
	)
	chatDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "chat_request_duration_seconds",
			Help:    "Chat request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"model"},
	)
	chatTokensTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "chat_tokens_generated_total",
			Help: "Total tokens generated by model",
		},
		[]string{"model"},
	)
)

func init() {
	prometheus.MustRegister(chatRequestsTotal, chatDuration, chatTokensTotal)
}

type chatRequest struct {
	Model          string              `json:"model"`
	ConversationID string              `json:"conversation_id,omitempty"`
	AgentSlug      string              `json:"agent_slug,omitempty"`
	Messages       []ollamaapi.Message `json:"messages"`
	Think          *bool               `json:"think,omitempty"`
	Options        map[string]any      `json:"options,omitempty"`
	Skills         []string            `json:"skills,omitempty"`
}

type chatHandler struct {
	defaultModel    string
	client          ChatClient
	imageStore      *ImageStore
	store           Store
	promptMerger    *PromptMerger
	shutdownCtx     context.Context
	bgTasks         *sync.WaitGroup
	eventBus        *sse.EventBus[Event]
	searcher        Searcher
	toolRouter      *ToolRouter
	taskRunner      TaskRunner
	weather         WeatherProvider
	pageFetcher     *PageFetcher
	searchQualifier *SearchQualifier
	tools           map[string]*ToolDef
	pollInterval    time.Duration
}

func newChatHandler(defaultModel string, client ChatClient, imageStore *ImageStore, store Store, promptMerger *PromptMerger, shutdownCtx context.Context, eventBus *sse.EventBus[Event]) *chatHandler {
	h := &chatHandler{
		defaultModel: defaultModel,
		client:       client,
		imageStore:   imageStore,
		store:        store,
		promptMerger: promptMerger,
		shutdownCtx:  shutdownCtx,
		bgTasks:      &sync.WaitGroup{},
		eventBus:     eventBus,
	}
	h.registerTools()
	return h
}

func (h *chatHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		axon.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, maxChatRequestSize)
	var req chatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		axon.WriteError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if len(req.Messages) == 0 {
		axon.WriteError(w, http.StatusBadRequest, "messages must not be empty")
		return
	}

	// Verify agent ownership — the requesting user must own the agent
	if req.AgentSlug != "" && h.store != nil {
		userID := axon.UserID(r.Context())
		if _, err := h.store.GetAgentByUser(userID, req.AgentSlug); err != nil {
			axon.WriteError(w, http.StatusNotFound, "agent not found")
			return
		}
	}

	model := req.Model
	if model == "" {
		model = h.defaultModel
	}

	if h.client == nil {
		axon.WriteError(w, http.StatusInternalServerError, "ollama client not configured")
		return
	}

	// Extract last user message content for persistence
	var userContent string
	for i := len(req.Messages) - 1; i >= 0; i-- {
		if req.Messages[i].Role == "user" {
			userContent = req.Messages[i].Content
			break
		}
	}

	tools := h.buildToolsForSkills(req.Skills)

	// Use tool router to filter tools based on user message
	if h.toolRouter != nil && len(tools) > 0 && userContent != "" {
		routed, err := h.toolRouter.Route(r.Context(), userContent, tools)
		if err != nil {
			slog.Warn("tool router error, proceeding without tools", "error", err)
		}
		tools = routed
	}

	h.streamChat(w, r, model, req.Messages, req.Think, req.Options, tools, req.ConversationID, userContent, req.AgentSlug)
}

// SSETaskEvent represents a task submission event sent to the frontend.
type SSETaskEvent struct {
	TaskID      string `json:"task_id"`
	Type        string `json:"type"`        // "claude_session" | "image_generation"
	Status      string `json:"status"`      // "queued" | "running"
	Description string `json:"description"`
}

type sseEvent struct {
	Content         string        `json:"content"`
	Thinking        string        `json:"thinking,omitempty"`
	Done            bool          `json:"done"`
	TotalDurationMs *int64        `json:"total_duration_ms,omitempty"`
	ImageURL        string        `json:"image_url,omitempty"`
	ImageID         string        `json:"image_id,omitempty"`
	NSFWDetected    bool          `json:"nsfw_detected,omitempty"`
	ToolUse         string        `json:"tool_use,omitempty"`
	Task            *SSETaskEvent `json:"task,omitempty"`
}

func (h *chatHandler) streamChat(w http.ResponseWriter, r *http.Request, model string, messages []ollamaapi.Message, think *bool, options map[string]any, tools ollamaapi.Tools, conversationID string, userContent string, agentSlug string) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		axon.WriteError(w, http.StatusInternalServerError, "streaming not supported")
		return
	}

	sse.SetSSEHeaders(w)

	start := time.Now()
	var tokenCount float64

	sendEvent := func(event sseEvent) {
		data, err := json.Marshal(event)
		if err != nil {
			return
		}
		fmt.Fprintf(w, "data: %s\n\n", data)
		flusher.Flush()
	}

	// Track final assistant output across tool-calling iterations
	var finalContent strings.Builder
	var finalThinking strings.Builder
	var imageRefs []map[string]string

	// Build stream filter matchers — tool call detection when tools are available
	var matchers []streamfilter.Matcher
	if len(tools) > 0 {
		matchers = append(matchers, streamfilter.NewToolCallMatcher())
	}

	// Tool calling loop — may iterate multiple times if model uses tools
	keepAlive := ollamaapi.Duration{Duration: -1} // keep model loaded indefinitely
	for {
		stream := true
		ollamaReq := &ollamaapi.ChatRequest{
			Model:     model,
			Messages:  messages,
			Stream:    &stream,
			Options:   options,
			Tools:     tools,
			KeepAlive: &keepAlive,
		}
		if think != nil {
			tv := ollamaapi.ThinkValue{Value: *think}
			ollamaReq.Think = &tv
		}

		var assistantContent strings.Builder
		var assistantThinking string
		var toolCalls []ollamaapi.ToolCall
		var streamKilled bool

		// Stream filter: small lookahead buffer that scans for tool call JSON
		// and content safety patterns, emitting tokens with a fixed delay.
		filter := streamfilter.NewStreamFilter(func(s string) {
			sendEvent(sseEvent{Content: s})
		}, matchers, streamfilter.DefaultMaxBuffer)

		err := h.client.Chat(r.Context(), ollamaReq, func(resp ollamaapi.ChatResponse) error {
			// Thinking tokens bypass the filter
			if resp.Message.Thinking != "" {
				assistantThinking += resp.Message.Thinking
				if !resp.Done {
					sendEvent(sseEvent{Thinking: resp.Message.Thinking})
				}
			}

			// Structured tool calls from Ollama handled directly
			if len(resp.Message.ToolCalls) > 0 {
				toolCalls = append(toolCalls, resp.Message.ToolCalls...)
			}

			if resp.Message.Content != "" {
				assistantContent.WriteString(resp.Message.Content)
				tokenCount++
			}
			if resp.Message.Thinking != "" {
				tokenCount++
			}

			// Don't forward done from inside the callback
			if resp.Done {
				return nil
			}

			// Feed content through the stream filter
			if resp.Message.Content != "" {
				action := filter.Write(resp.Message.Content)
				switch a := action.(type) {
				case streamfilter.ToolCallAction:
					toolCalls = append(toolCalls, convertToolCalls(a.Calls)...)
				case streamfilter.KillAction:
					streamKilled = true
					slog.Warn("stream killed by filter", "reason", a.Reason)
					return fmt.Errorf("stream killed: %s", a.Reason)
				}
			}

			return nil
		})

		if err != nil && !streamKilled {
			chatRequestsTotal.WithLabelValues(model, "error").Inc()
			slog.Error("ollama chat error", "error", err, "model", model)
			sendEvent(sseEvent{Content: "Error: " + err.Error(), Done: true})
			return
		}

		if streamKilled {
			sendEvent(sseEvent{Content: "\n\nI need to stop here.", Done: true})
			return
		}

		// Flush remaining buffer — may detect tool calls in final content
		action := filter.Flush()
		switch a := action.(type) {
		case streamfilter.ToolCallAction:
			toolCalls = append(toolCalls, convertToolCalls(a.Calls)...)
		case streamfilter.KillAction:
			slog.Warn("stream killed on flush", "reason", a.Reason)
			sendEvent(sseEvent{Content: "\n\nI need to stop here.", Done: true})
			return
		}

		content := assistantContent.String()
		// If tool calls were extracted from content, don't count the JSON as content
		if len(toolCalls) > 0 {
			content = ""
		}

		finalContent.WriteString(content)
		finalThinking.WriteString(assistantThinking)

		// If no tool calls, we're done
		if len(toolCalls) == 0 {
			break
		}

		// Append assistant message with tool calls to history
		assistantMsg := ollamaapi.Message{
			Role:      "assistant",
			Content:   assistantContent.String(),
			Thinking:  assistantThinking,
			ToolCalls: toolCalls,
		}
		messages = append(messages, assistantMsg)

		// Execute each tool call via registry
		userID := axon.UserID(r.Context())
		// Extract system prompt from message history for tool context
		var systemPromptForTools string
		if len(messages) > 0 && messages[0].Role == "system" {
			systemPromptForTools = messages[0].Content
		}
		username := axon.Username(r.Context())
		toolCtx := ToolContext{
			Handler:        h,
			Request:        r,
			AgentSlug:      agentSlug,
			ConversationID: conversationID,
			UserID:         userID,
			Username:       username,
			SystemPrompt:   systemPromptForTools,
			SendEvent:      sendEvent,
			ImageRefs:      &imageRefs,
		}

		for _, tc := range toolCalls {
			// Send a human-readable description of the tool call as content
			desc := describeToolCall(tc)
			if desc != "" {
				sendEvent(sseEvent{Content: desc})
			}
			sendEvent(sseEvent{ToolUse: tc.Function.Name})

			if tool, ok := h.tools[tc.Function.Name]; ok {
				result := tool.Execute(&toolCtx, tc.Function.Arguments)
				messages = append(messages, ollamaapi.Message{
					Role:    "tool",
					Content: result.Content,
				})
			} else {
				slog.Warn("unknown tool called", "tool", tc.Function.Name)
				messages = append(messages, ollamaapi.Message{
					Role:    "tool",
					Content: fmt.Sprintf("Error: unknown tool %q", tc.Function.Name),
				})
			}
		}

		// Continue the loop — model will generate follow-up text
	}

	doneMs := time.Since(start).Milliseconds()
	sendEvent(sseEvent{Done: true, TotalDurationMs: &doneMs})

	duration := time.Since(start).Seconds()
	chatDuration.WithLabelValues(model).Observe(duration)
	chatRequestsTotal.WithLabelValues(model, "ok").Inc()
	chatTokensTotal.WithLabelValues(model).Add(tokenCount)

	if conversationID != "" && h.store != nil {
		durationMs := time.Since(start).Milliseconds()

		h.store.AppendMessage(conversationID, Message{
			Role:    "user",
			Content: userContent,
		})

		assistantMsg := Message{
			Role:       "assistant",
			Content:    finalContent.String(),
			Thinking:   finalThinking.String(),
			DurationMs: &durationMs,
		}
		if len(imageRefs) > 0 {
			imagesJSON, _ := json.Marshal(imageRefs)
			assistantMsg.Images = string(imagesJSON)
		}
		h.store.AppendMessage(conversationID, assistantMsg)

		userID := axon.UserID(r.Context())
		conv, err := h.store.GetConversationByUser(userID, conversationID)
		if err == nil && conv.Title == nil {
			h.bgTasks.Add(1)
			go func() {
				defer h.bgTasks.Done()
				h.generateTitle(h.shutdownCtx, userID, conversationID, userContent, finalContent.String())
			}()
		}
	}
}

func (h *chatHandler) generateTitle(shutdownCtx context.Context, userID string, conversationID string, userMsg string, assistantMsg string) {
	ctx, cancel := context.WithTimeout(shutdownCtx, 30*time.Second)
	defer cancel()

	titlePrompt := []ollamaapi.Message{
		{Role: "system", Content: "Generate a very short title (3-5 words) for this conversation. Respond with only the title, nothing else."},
		{Role: "user", Content: userMsg},
		{Role: "assistant", Content: assistantMsg},
		{Role: "user", Content: "What is a good 3-5 word title for this conversation?"},
	}

	stream := false
	var title strings.Builder
	err := h.client.Chat(ctx, &ollamaapi.ChatRequest{
		Model:    h.defaultModel,
		Messages: titlePrompt,
		Stream:   &stream,
	}, func(resp ollamaapi.ChatResponse) error {
		title.WriteString(resp.Message.Content)
		return nil
	})

	if ctx.Err() != nil {
		slog.Info("title generation cancelled", "conversation_id", conversationID, "reason", ctx.Err())
		return
	}

	if err != nil {
		slog.Warn("title generation failed", "conversation_id", conversationID, "error", err)
		return
	}
	titleStr := sanitizeTitle(title.String())
	if titleStr != "" {
		h.store.UpdateConversationTitle(userID, conversationID, titleStr)
	}
}

// sanitizeTitle cleans up LLM-generated titles by stripping quotes and markdown.
func sanitizeTitle(raw string) string {
	s := strings.TrimSpace(raw)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			s = s[1 : len(s)-1]
		}
	}
	s = strings.TrimPrefix(s, "**")
	s = strings.TrimSuffix(s, "**")
	return strings.TrimSpace(s)
}

// submitImageTask merges the prompt, encodes the reference image, and submits
// an image generation task to the task runner. Returns a ToolResult for the calling tool.
func (h *chatHandler) submitImageTask(ctx *ToolContext, promptStr string, private bool) ToolResult {
	imageID := uuid.New().String()

	// Merge prompt using LLM if merger is available
	finalPrompt := promptStr
	if h.promptMerger != nil {
		var recentMessages []Message
		if ctx.ConversationID != "" && h.store != nil {
			if msgs, err := h.store.GetRecentMessages(ctx.ConversationID, 5); err == nil {
				recentMessages = msgs
			}
		}

		var merged string
		var err error
		if private {
			merged, err = h.promptMerger.MergePromptPrivate(ctx.SystemPrompt, recentMessages, promptStr)
		} else {
			merged, err = h.promptMerger.MergePrompt(ctx.SystemPrompt, recentMessages, promptStr)
		}
		if err == nil {
			finalPrompt = merged
		} else {
			slog.Warn("prompt merge failed, using raw scene prompt", "error", err)
		}
	}

	// Load and base64-encode reference image for face consistency
	var refImageB64 string
	if ctx.AgentSlug != "" && h.store != nil && h.imageStore != nil {
		if baseImg, err := h.store.GetBaseImageByUser(ctx.UserID, ctx.AgentSlug); err == nil && baseImg != nil {
			if imgData, err := h.imageStore.Load(baseImg.ID); err == nil {
				refImageB64 = base64Encode(imgData)
			} else {
				slog.Warn("failed to load base image", "error", err, "base_image_id", baseImg.ID)
			}
		}
	}

	// Submit to task runner
	submission := &ImageTaskSubmission{
		Prompt:         finalPrompt,
		ReferenceImage: refImageB64,
		AgentSlug:      ctx.AgentSlug,
		UserID:         ctx.UserID,
		ConversationID: ctx.ConversationID,
		ImageID:        imageID,
		Private:        private,
	}

	_, err := h.taskRunner.SubmitTask(context.Background(), NewImageTaskRequest(submission))
	if err != nil {
		slog.Error("failed to submit image task", "error", err, "image_id", imageID)
		return ToolResult{Content: "Error: failed to submit image generation task"}
	}

	// Notify UI only after successful submission
	ctx.SendEvent(sseEvent{Task: &SSETaskEvent{
		TaskID:      imageID,
		Type:        "image_generation",
		Status:      "running",
		Description: "Generating image...",
	}})

	// Poll for completion in background (same pattern as use_claude tasks)
	h.bgTasks.Add(1)
	go func() {
		defer h.bgTasks.Done()
		h.pollTaskCompletion(imageID)
	}()

	pipelineLabel := "Image"
	if private {
		pipelineLabel = "Image (private pipeline)"
	}
	return ToolResult{Content: fmt.Sprintf("%s generation started, it will appear shortly.", pipelineLabel)}
}

// pollTaskCompletion polls the task runner for a task's status and publishes an event when done.
func (h *chatHandler) pollTaskCompletion(taskID string) {
	interval := h.pollInterval
	if interval == 0 {
		interval = 10 * time.Second
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	timeout := time.After(12 * time.Minute)

	for {
		select {
		case <-ticker.C:
			status, err := h.taskRunner.GetTaskStatus(h.shutdownCtx, taskID)
			if err != nil {
				slog.Warn("failed to poll task status", "task_id", taskID, "error", err)
				continue
			}

			switch status.Status {
			case "completed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID:  taskID,
						Status:  "completed",
						Summary: status.Summary,
					}})
				}
				return
			case "failed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID: taskID,
						Status: "failed",
						Error:  status.Error,
					}})
				}
				return
			}
		case <-timeout:
			slog.Warn("task polling timed out", "task_id", taskID)
			if h.eventBus != nil {
				h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
					TaskID: taskID,
					Status: "failed",
					Error:  "timed out waiting for task completion",
				}})
			}
			return
		case <-h.shutdownCtx.Done():
			return
		}
	}
}

// dayOrNight returns a human-readable time-of-day string.
func dayOrNight(isDay bool) string {
	if isDay {
		return "Daytime"
	}
	return "Nighttime"
}

// WaitForBackgroundTasks blocks until all background tasks complete.
func (h *chatHandler) WaitForBackgroundTasks() {
	h.bgTasks.Wait()
}

// base64Encode encodes raw bytes to a base64 string.
func base64Encode(data []byte) string {
	return base64.StdEncoding.EncodeToString(data)
}

// convertToolCalls converts provider-agnostic streamfilter.ToolCall to ollamaapi.ToolCall.
func convertToolCalls(calls []streamfilter.ToolCall) []ollamaapi.ToolCall {
	result := make([]ollamaapi.ToolCall, len(calls))
	for i, tc := range calls {
		args := ollamaapi.NewToolCallFunctionArguments()
		for k, v := range tc.Arguments {
			args.Set(k, v)
		}
		result[i] = ollamaapi.ToolCall{
			Function: ollamaapi.ToolCallFunction{
				Name:      tc.Name,
				Arguments: args,
			},
		}
	}
	return result
}

// describeToolCall returns a human-readable description of a tool call
// that can be shown to the user as an agent message.
func describeToolCall(tc ollamaapi.ToolCall) string {
	name := tc.Function.Name
	args := tc.Function.Arguments

	switch name {
	case "web_search":
		if q, ok := args.Get("query"); ok {
			return fmt.Sprintf("\n\n*Searching for \"%v\"...*\n\n", q)
		}
		return "\n\n*Searching the web...*\n\n"
	case "fetch_page":
		if u, ok := args.Get("url"); ok {
			return fmt.Sprintf("\n\n*Reading %v...*\n\n", u)
		}
		return "\n\n*Reading a web page...*\n\n"
	case "take_photo":
		return "\n\n*Taking a photo...*\n\n"
	case "check_weather":
		if loc, ok := args.Get("location"); ok {
			return fmt.Sprintf("\n\n*Checking weather for %v...*\n\n", loc)
		}
		return "\n\n*Checking the weather...*\n\n"
	case "current_time":
		return "\n\n*Checking the time...*\n\n"
	case "use_claude":
		return "\n\n*Submitting a code change...*\n\n"
	default:
		return fmt.Sprintf("\n\n*Using %s...*\n\n", name)
	}
}
