package chat //  (NSFW detector is a safety feature)

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
	"strings"
	"sync"
	"time"

	"github.com/benaskins/axon"
	agent "github.com/benaskins/axon-agent"
	tool "github.com/benaskins/axon-tool"
	"github.com/benaskins/axon/sse"

	ollamaapi "github.com/ollama/ollama/api"
	"github.com/prometheus/client_golang/prometheus"
)

const maxChatRequestSize = 1 << 20 // 1MB

var (
	chatRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "chat_requests_total",
			Help: "Total chat requests by model and status",
		},
		[]string{"model", "status"},
	)
	chatDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "chat_request_duration_seconds",
			Help:    "Chat request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"model"},
	)
	chatTokensTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "chat_tokens_generated_total",
			Help: "Total tokens generated by model",
		},
		[]string{"model"},
	)
)

func init() {
	prometheus.MustRegister(chatRequestsTotal, chatDuration, chatTokensTotal)
}

type chatRequest struct {
	Model          string              `json:"model"`
	ConversationID string              `json:"conversation_id,omitempty"`
	AgentSlug      string              `json:"agent_slug,omitempty"`
	Messages       []ollamaapi.Message `json:"messages"`
	Think          *bool               `json:"think,omitempty"`
	Options        map[string]any      `json:"options,omitempty"`
	Skills         []string            `json:"skills,omitempty"`
}

type chatHandler struct {
	defaultModel    string
	client          ChatClient
	adapter         *OllamaAdapter
	store           Store
	shutdownCtx     context.Context
	bgTasks         *sync.WaitGroup
	eventBus        *sse.EventBus[Event]
	searcher        Searcher
	toolRouter      *ToolRouter
	taskRunner      TaskRunner
	weather         WeatherProvider
	pageFetcher     *PageFetcher
	searchQualifier *SearchQualifier
	extraTools      map[string]tool.ToolDef
	memoryRecaller  MemoryRecaller
	idleExtractor   *IdleExtractor
	analytics       AnalyticsEmitter
	pollInterval    time.Duration
}

func newChatHandler(defaultModel string, client ChatClient, store Store, shutdownCtx context.Context, eventBus *sse.EventBus[Event]) *chatHandler {
	h := &chatHandler{
		defaultModel: defaultModel,
		client:       client,
		store:        store,
		shutdownCtx:  shutdownCtx,
		bgTasks:      &sync.WaitGroup{},
		eventBus:     eventBus,
	}
	if client != nil {
		h.adapter = NewOllamaAdapter(client)
	}
	return h
}

func (h *chatHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		axon.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}

	r.Body = http.MaxBytesReader(w, r.Body, maxChatRequestSize)
	var req chatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		axon.WriteError(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if len(req.Messages) == 0 {
		axon.WriteError(w, http.StatusBadRequest, "messages must not be empty")
		return
	}

	// Verify agent ownership — the requesting user must own the agent
	if req.AgentSlug != "" && h.store != nil {
		userID := axon.UserID(r.Context())
		if _, err := h.store.GetAgentByUser(userID, req.AgentSlug); err != nil {
			axon.WriteError(w, http.StatusNotFound, "agent not found")
			return
		}
	}

	model := req.Model
	if model == "" {
		model = h.defaultModel
	}

	if h.client == nil {
		axon.WriteError(w, http.StatusInternalServerError, "ollama client not configured")
		return
	}

	// Extract last user message content for persistence
	var userContent string
	for i := len(req.Messages) - 1; i >= 0; i-- {
		if req.Messages[i].Role == "user" {
			userContent = req.Messages[i].Content
			break
		}
	}

	h.runAgent(w, r, model, req.Messages, req.Think, req.Options, req.Skills, req.ConversationID, userContent, req.AgentSlug)
}

// SSETaskEvent represents a task submission event sent to the frontend.
type SSETaskEvent struct {
	TaskID      string `json:"task_id"`
	Type        string `json:"type"`        // "claude_session" | "image_generation"
	Status      string `json:"status"`      // "queued" | "running"
	Description string `json:"description"`
}

type sseEvent struct {
	Content         string        `json:"content"`
	Thinking        string        `json:"thinking,omitempty"`
	Done            bool          `json:"done"`
	TotalDurationMs *int64        `json:"total_duration_ms,omitempty"`
	ToolUse         string        `json:"tool_use,omitempty"`
	Task            *SSETaskEvent `json:"task,omitempty"`
}

func (h *chatHandler) runAgent(w http.ResponseWriter, r *http.Request, model string, messages []ollamaapi.Message, think *bool, options map[string]any, skills []string, conversationID string, userContent string, agentSlug string) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		axon.WriteError(w, http.StatusInternalServerError, "streaming not supported")
		return
	}

	sse.SetSSEHeaders(w)

	start := time.Now()
	var tokenCount float64

	sendEvent := func(event sseEvent) {
		data, err := json.Marshal(event)
		if err != nil {
			return
		}
		fmt.Fprintf(w, "data: %s\n\n", data)
		flusher.Flush()
	}

	// Convert Ollama messages to agent messages
	agentMessages := ollamaMessagesToAgent(messages)

	// Extract system prompt for tool context
	var systemPrompt string
	if len(agentMessages) > 0 && agentMessages[0].Role == "system" {
		systemPrompt = agentMessages[0].Content
	}

	// Build tool map from skills
	tools := h.buildToolMap(skills, sendEvent, r, agentSlug, conversationID, systemPrompt)

	// Use tool router to filter tools based on user message
	if h.toolRouter != nil && len(tools) > 0 && userContent != "" {
		toolDefs := toolDefsFromMap(tools)
		routed, err := h.toolRouter.Route(r.Context(), userContent, toolDefsToOllama(toolDefs))
		if err != nil {
			slog.Warn("tool router error, proceeding with all tools", "error", err)
		} else {
			tools = filterToolMap(tools, routed)
		}
	}

	// Build the agent request
	agentReq := &agent.ChatRequest{
		Model:    model,
		Messages: agentMessages,
		Stream:   true,
		Think:    think,
		Options:  options,
	}

	// Build tool context
	userID := axon.UserID(r.Context())
	username := axon.Username(r.Context())
	toolCtx := &tool.ToolContext{
		Ctx:            r.Context(),
		UserID:         userID,
		Username:       username,
		AgentSlug:      agentSlug,
		ConversationID: conversationID,
		SystemPrompt:   systemPrompt,
	}

	// Wire callbacks to SSE
	cb := agent.Callbacks{
		OnToken: func(token string) {
			tokenCount++
			sendEvent(sseEvent{Content: token})
		},
		OnThinking: func(token string) {
			tokenCount++
			sendEvent(sseEvent{Thinking: token})
		},
		OnToolUse: func(name string, args map[string]any) {
			desc := describeToolUse(name, args)
			if desc != "" {
				sendEvent(sseEvent{Content: desc})
			}
			sendEvent(sseEvent{ToolUse: name})
		},
		OnDone: func(durationMs int64) {
			sendEvent(sseEvent{Done: true, TotalDurationMs: &durationMs})
		},
	}

	// Run the conversation loop
	result, err := agent.Run(r.Context(), h.adapter, agentReq, tools, toolCtx, cb)
	if err != nil {
		chatRequestsTotal.WithLabelValues(model, "error").Inc()
		slog.Error("agent run error", "error", err, "model", model)
		sendEvent(sseEvent{Content: "Error: " + err.Error(), Done: true})
		return
	}

	// Metrics
	duration := time.Since(start).Seconds()
	chatDuration.WithLabelValues(model).Observe(duration)
	chatRequestsTotal.WithLabelValues(model, "ok").Inc()
	chatTokensTotal.WithLabelValues(model).Add(tokenCount)

	// Analytics
	durationMs := time.Since(start).Milliseconds()
	if h.analytics != nil && agentSlug != "" {
		runID := axon.RunID(r.Context())
		userEvt := MessageEvent(agentSlug, userID, conversationID, "user", 0)
		userEvt.RunID = runID
		assistantEvt := MessageEvent(agentSlug, userID, conversationID, "assistant", durationMs)
		assistantEvt.RunID = runID
		h.analytics.Emit(userEvt, assistantEvt)
	}

	// Persist
	if conversationID != "" && h.store != nil {
		h.store.AppendMessage(conversationID, Message{
			Role:    "user",
			Content: userContent,
		})

		assistantMsg := Message{
			Role:       "assistant",
			Content:    result.Content,
			Thinking:   result.Thinking,
			DurationMs: &durationMs,
		}
		h.store.AppendMessage(conversationID, assistantMsg)

		if h.idleExtractor != nil && agentSlug != "" {
			h.idleExtractor.Touch(conversationID, agentSlug, userID)
		}

		conv, err := h.store.GetConversationByUser(userID, conversationID)
		if err == nil && conv.Title == nil {
			h.bgTasks.Add(1)
			go func() {
				defer h.bgTasks.Done()
				h.generateTitle(h.shutdownCtx, userID, conversationID, userContent, result.Content)
			}()
		}
	}
}

// ollamaMessagesToAgent converts Ollama messages to agent messages.
func ollamaMessagesToAgent(msgs []ollamaapi.Message) []agent.Message {
	result := make([]agent.Message, len(msgs))
	for i, m := range msgs {
		result[i] = agent.Message{
			Role:    m.Role,
			Content: m.Content,
		}
	}
	return result
}

// describeToolUse returns a human-readable description of a tool call.
func describeToolUse(name string, args map[string]any) string {
	switch name {
	case "web_search":
		if q, ok := args["query"].(string); ok {
			return fmt.Sprintf("\n\n*Searching for \"%s\"...*\n\n", q)
		}
		return "\n\n*Searching the web...*\n\n"
	case "fetch_page":
		if u, ok := args["url"].(string); ok {
			return fmt.Sprintf("\n\n*Reading %s...*\n\n", u)
		}
		return "\n\n*Reading a web page...*\n\n"
	case "check_weather":
		if loc, ok := args["location"].(string); ok {
			return fmt.Sprintf("\n\n*Checking weather for %s...*\n\n", loc)
		}
		return "\n\n*Checking the weather...*\n\n"
	case "current_time":
		return "\n\n*Checking the time...*\n\n"
	case "use_claude":
		return "\n\n*Submitting a code change...*\n\n"
	default:
		return fmt.Sprintf("\n\n*Using %s...*\n\n", name)
	}
}

// toolDefsFromMap extracts ToolDef slice from a map.
func toolDefsFromMap(m map[string]tool.ToolDef) []tool.ToolDef {
	defs := make([]tool.ToolDef, 0, len(m))
	for _, d := range m {
		defs = append(defs, d)
	}
	return defs
}

// toolDefsToOllama converts tool.ToolDef to Ollama tools for the ToolRouter.
func toolDefsToOllama(defs []tool.ToolDef) ollamaapi.Tools {
	return toOllamaToolDefs(defs)
}

// filterToolMap returns a subset of tools matching the routed Ollama tools.
func filterToolMap(all map[string]tool.ToolDef, routed ollamaapi.Tools) map[string]tool.ToolDef {
	result := make(map[string]tool.ToolDef)
	for _, t := range routed {
		name := t.Function.Name
		if def, ok := all[name]; ok {
			result[name] = def
		}
	}
	return result
}

func (h *chatHandler) generateTitle(shutdownCtx context.Context, userID string, conversationID string, userMsg string, assistantMsg string) {
	ctx, cancel := context.WithTimeout(shutdownCtx, 30*time.Second)
	defer cancel()

	titlePrompt := []ollamaapi.Message{
		{Role: "system", Content: "Generate a very short title (3-5 words) for this conversation. Respond with only the title, nothing else."},
		{Role: "user", Content: userMsg},
		{Role: "assistant", Content: assistantMsg},
		{Role: "user", Content: "What is a good 3-5 word title for this conversation?"},
	}

	stream := false
	var title strings.Builder
	err := h.client.Chat(ctx, &ollamaapi.ChatRequest{
		Model:    h.defaultModel,
		Messages: titlePrompt,
		Stream:   &stream,
	}, func(resp ollamaapi.ChatResponse) error {
		title.WriteString(resp.Message.Content)
		return nil
	})

	if ctx.Err() != nil {
		slog.Info("title generation cancelled", "conversation_id", conversationID, "reason", ctx.Err())
		return
	}

	if err != nil {
		slog.Warn("title generation failed", "conversation_id", conversationID, "error", err)
		return
	}
	titleStr := sanitizeTitle(title.String())
	if titleStr != "" {
		h.store.UpdateConversationTitle(userID, conversationID, titleStr)
	}
}

// sanitizeTitle cleans up LLM-generated titles by stripping quotes and markdown.
func sanitizeTitle(raw string) string {
	s := strings.TrimSpace(raw)
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			s = s[1 : len(s)-1]
		}
	}
	s = strings.TrimPrefix(s, "**")
	s = strings.TrimSuffix(s, "**")
	return strings.TrimSpace(s)
}

// pollTaskCompletion polls the task runner for a task's status and publishes an event when done.
func (h *chatHandler) pollTaskCompletion(taskID string) {
	interval := h.pollInterval
	if interval == 0 {
		interval = 10 * time.Second
	}
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	timeout := time.After(12 * time.Minute)

	for {
		select {
		case <-ticker.C:
			status, err := h.taskRunner.GetTaskStatus(h.shutdownCtx, taskID)
			if err != nil {
				slog.Warn("failed to poll task status", "task_id", taskID, "error", err)
				continue
			}

			switch status.Status {
			case "completed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID:  taskID,
						Status:  "completed",
						Summary: status.Summary,
					}})
				}
				return
			case "failed":
				if h.eventBus != nil {
					h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
						TaskID: taskID,
						Status: "failed",
						Error:  status.Error,
					}})
				}
				return
			}
		case <-timeout:
			slog.Warn("task polling timed out", "task_id", taskID)
			if h.eventBus != nil {
				h.eventBus.Publish(Event{Type: "task", Task: &TaskEvent{
					TaskID: taskID,
					Status: "failed",
					Error:  "timed out waiting for task completion",
				}})
			}
			return
		case <-h.shutdownCtx.Done():
			return
		}
	}
}

// dayOrNight returns a human-readable time-of-day string.
func dayOrNight(isDay bool) string {
	if isDay {
		return "Daytime"
	}
	return "Nighttime"
}

// WaitForBackgroundTasks blocks until all background tasks complete.
// Also flushes any pending idle extractions.
func (h *chatHandler) WaitForBackgroundTasks() {
	if h.idleExtractor != nil {
		h.idleExtractor.FlushAll()
	}
	h.bgTasks.Wait()
}


